config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  resources :post_hobbies do
    get "drafts", on: :collection
    resources :comments,  only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    get :favorites, on: :collection
  end

  resources :users, only: [:index,:show, :edit, :update] do
    get   "confirm_withdraw"
    patch "withdraw"
  end

  resources :searches, only: [:index]

  resources :groups, only: [:new, :create, :index, :show, :edit, :update] do
    resources :group_users, only: [:create, :destroy]
    resources :chats, only: [:create]
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all

    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :message, presence: true,  length:{maximum:140}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post_hobby
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_hobby

  validates_uniqueness_of :hobby_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: "User"

  has_many :chats,       dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :users,       through: :group_users, source: :user

  has_one_attached :group_image

  validates :name,         presence: true
  validates :introduction, presence: true

  def is_owned_by?(user)
      owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/post_hobby.rb
class PostHobby < ApplicationRecord

  belongs_to  :user

  has_many  :comments,  dependent: :destroy
  has_many  :favorites, dependent: :destroy
  has_many  :post_tags, dependent: :destroy
  has_many  :tags,      through:   :post_tags

  has_one_attached :image, dependent: :destroy

  validates  :title,    presence: true
  validates  :text,     presence: true, length:{maximum:200}



  enum post_status: { published: 0, draft: 1 }

  def save_draft
    self.post_status = :draft
    save(validate: false)
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def save_tags(sent_tags)
    # 現在のユーザーの持っているskillを引っ張ってきている
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 今持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - sent_tags
    # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
    new_tags = sent_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      post_hobby_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << post_hobby_tag
    end
  end

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end




end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post_hobby
  belongs_to :tag
  validates :post_hobby_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :post_hobbies, through: :post_tags

  validates  :name, presence: true, uniqueness: true


  scope :merge_post_hobbies, -> (tags){ }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_hobbies
  has_many :comments,    dependent: :destroy
  has_many :favorites,   dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups,      through:   :group_users
  has_many :chats

  has_one_attached :profile_image

  validates :name,  length: { minimum:2, maximum:20 }, uniqueness: true
  validates :hobby, length: { maximum:50 }

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="row justify-content-end">
    <div class="col-1">
      <div class="nav">
        <input id="drawer-input" class="drawer-hidden" type="checkbox">
        <label for="drawer-input" class="drawer-open row justify-content-center"><span></span></label>
        <nav class="nav-content">
          <ul class="nav-list">
            <% if current_user.admin? %>
              <li class="nav-item"><%= link_to 'ユーザ一覧', users_path, class: "text-light" %></li>
              <li class="nav-item"><%= link_to '投稿一覧', post_hobbies_path, class: "text-light" %></li>
              <li class="nav-item"><%= link_to 'グループ一覧', groups_path, class: "text-light" %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-light" %></li>
              <li>
                <%= link_to '管理者', rails_admin_path %>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to 'マイページ', user_path(current_user), class: "text-light" %></li>
              <li class="nav-item"><%= link_to '投稿一覧', post_hobbies_path, class: "text-light" %></li>
              <li class="nav-item"><%= link_to 'グループ', groups_path, class: "text-light" %></li>
              <li class="nav-item"><%= link_to 'お気に入り', favorites_post_hobbies_path, class: "text-light" %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-light" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LHF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag params[:controller], 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">
    <header>
      <%= render 'layouts/header' %>
    </header>

    <main>
      <div class="container-fuild">
        <p class="<%= flash[:color] %>"><%= notice %></p>
        <%= yield %>
      </div>
    </main>

    <footer>

    </footer>
  </body>
</html>