config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  devise_scope :user do
    post 'users/guest_sign_in', to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  resources :post_hobbies do
    get "drafts", on: :collection
    resources :comments,  only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    get :favorites, on: :collection
  end

  resources :users, only: [:index,:show, :edit, :update] do
    get   "confirm_withdraw"
    patch "withdraw"
  end

  resources :searches, only: [:index]

  resources :groups, only: [:new, :create, :index, :show, :edit, :update] do
    resources :group_users, only: [:create, :destroy]
    resources :chats, only: [:create]
  end

end

app/models/post_hobby.rb
class PostHobby < ApplicationRecord

  belongs_to  :user

  has_many  :comments,  dependent: :destroy
  has_many  :favorites, dependent: :destroy
  has_many  :post_tags, dependent: :destroy
  has_many  :tags,      through:   :post_tags

  has_one_attached :image, dependent: :destroy

  validates  :title,    presence: true
  validates  :text,     presence: true, length:{maximum:200}



  enum post_status: { published: 0, draft: 1 }

  def save_draft
    self.post_status = :draft
    save(validate: false)
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def save_tags(sent_tags)
    # 現在のユーザーの持っているskillを引っ張ってきている
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 今持っているタグと今回保存されたものの差をすでにあるタグとする。古いタグは消す。
    old_tags = current_tags - sent_tags
    # 今回保存されたものと現在の差を新しいタグとする。新しいタグは保存
    new_tags = sent_tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # Create new taggings:
    new_tags.each do |new_name|
      post_hobby_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << post_hobby_tag
    end
  end

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end




end

app/controllers/post_hobbies_controller.rb
class PostHobbiesController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @post_hobby = PostHobby.new
    @isDraft = @post_hobby.draft?
  end

  def create
    if params[:commit] == "下書き保存"
      @post_hobby = PostHobby.create(post_hobby_params.merge(user_id: current_user.id))
      if @post_hobby.save_draft
        redirect_to drafts_post_hobbies_path
      else
        render :new
      end
    else
      @post_hobby = PostHobby.create(post_hobby_params.merge(user_id: current_user.id))
      tag_list = params[:post_hobby][:name].split(',')
      if tag_list == []
        tag = Tag.new()
        tag.name = ""
        tag.save
        render :new
      elsif @post_hobby.save
        @post_hobby.save_tags(tag_list)
        redirect_to post_hobby_path(@post_hobby)
      else
        render :new
      end
    end
  end

  def index
    @published_post_hobbies = PostHobby.where(user_id: current_user.id).where(post_status: :published).order(created_at: :desc)
    @tag_list = Tag.all
  end

  def show
    @post_hobby = PostHobby.find(params[:id])
  end

  def edit
    @post_hobby = PostHobby.find(params[:id])
    @isDraft = @post_hobby.draft?
    @tag_list=@post_hobby.tags.pluck(:name).join(',')
  end

  def update
    @post_hobby = PostHobby.find(params[:id])
    tag_list = params[:post_hobby][:name].split(',')
    if @post_hobby.update(post_hobby_params)
      if params[:commit] == "下書き保存"
        @post_hobby.update(post_status: :draft)
        redirect_to post_hobbies_path, notice: "下書きを保存しました。"
      elsif tag_list == []
       tag = Tag.new()
        tag.name = ""
        tag.save
        render :edit
      else
        @post_hobby.update(post_status: :published)
        @old_relations = PostTag.where(post_hobby_id: @post_hobby.id)
        @old_relations.each do |relation|
          relation.delete
        end
        @post_hobby.save_tags(tag_list)
        redirect_to @post_hobby, notice: "投稿を更新しました。"
      end
    else
      render :edit
    end
  end

  def drafts
    @draft_post_hobbies = PostHobby.where(user_id: current_user.id).where(post_status: :draft).order(created_at: :desc)
  end

  private

  def post_hobby_params
    params.require(:post_hobby).permit(:title, :text, :image, :post_status)
  end

  def ensure_correct_user
    @post_hobby = PostHobby.find(params[:id])
    unless @post_hobby.user == current_user
      redirect_to post_hobbiess_path
    end
  end

end

app/helpers/post_hobbies_helper.rb
module PostHobbiesHelper
end

app/views/post_hobbies/_form.html.erb
<%= form_with model: post_hobby, local: true do |f| %>
  <div class="form-group">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :文章 %>
    <%= f.text_area :text %>
  </div>
  <div class="form-group">
    <%= f.label :画像 %>
    <%= f.file_field :image, accept: 'image/*' %>
  </div>
  <div class="form-group">
    <%= f.label :タグ %>
    <%= f.text_field :name, value: tag_list %>
  </div>
  <div class="form-group">
    <%= f.submit '投稿する', name: 'commit' ,class: "btn btn-success"%>
    <% if post_hobby.new_record? || isDraft %>
      <%= f.submit '下書き保存', name: 'commit',class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/post_hobbies/_index.html.erb
<% obj.each do |obj| %>

  <div class="card">
    <input id="read" class="lower-btn" type="checkbox"/>
    <label for="read" class="lower"></label>

      <div class="card-head">
        <%= image_tag obj.get_image %>
      </div>

      <div class="card-body">
      <h4 class="card-title"><%= link_to obj.title, post_hobby_path(obj) %></h4>
      <div class="card-text">
        <p>
        <%= obj.text %>
        <%= obj.tags.map(&:name).join(',') %>
        <%= obj.post_status_i18n %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/post_hobbies/drafts.html.erb
<div class="row">
  <div class="col-10 offset-1">
    <h3>下書き</h3>
    <table class="table">
      <% @draft_post_hobbies.each do |draft| %>
        <tr>
          <td><%= image_tag draft.get_image, size: '200x100', class: "image" %></td>
          <td><%= draft.title %></td>
          <td><%= draft.text %></td>
          <td><%= link_to '編集する', edit_post_hobby_path(draft), class: "text-primary" %></td>
          <td><%= draft.post_status_i18n %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/post_hobbies/edit.html.erb
<div class="row">
  <div class="col-5 offset-2">
    <h3>投稿編集画面</h3>
    <%= render 'form', post_hobby: @post_hobby, isDraft: @isDraft, tag_list: @tag_list %>
  </div>
</div>

app/views/post_hobbies/index.html.erb
<div class="row">
  <div class="col-3 offset-1">
    <p>&plus;  <%= link_to '新規登録する', new_post_hobby_path %></p>
    <p>&lt;  <%= link_to '下書き一覧へ', drafts_post_hobbies_path %></p>
  </div>
  <div class="col-6 offset-1">
    <h3 class="mb-3">投稿一覧</h3>
    <%= render 'index', obj: @published_post_hobbies %>
  </div>
</div>

app/views/post_hobbies/new.html.erb
<div class="row">
  <div class="col-5 offset-2">
    <h3>新規投稿画面</h3>
    <%= render 'form', post_hobby: @post_hobby, isDraft: @isDraft, tag_list: @tag_list %>
  </div>
</div>

app/views/post_hobbies/show.html.erb
<div class="row">
  <div class="col-5">
    <div class="img">

      <%= link_to '編集する', edit_post_hobby_path(@post_hobby), class: "text-primary" %>
    </div>
  </div>
  <div class="col-5 offset-1">

  </div>
</div>